spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/domaindns?useSSL=true&serverTimezone=UTC&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PASS}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
logging:
  level:
    root: INFO
    com.domaindns: INFO
server:
  port: 8080
cors:
  allow-origins: "https://your-admin.example.com,https://your-app.example.com"

secrets:
  aes-key: ${SECRETS_AES_KEY}