spring:
  datasource:
    url: jdbc:mysql://localhost:3306/domaindns?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: hyper
    password: 1010411661
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mail:
    host: smtp.qq.com
    port: 587
    username: 1010411661@qq.com
    password: twrhmnwlvoxgbfji
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 587
        debug: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
logging:
  level:
    root: INFO
    com.domaindns: DEBUG
    org.mybatis: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
server:
  port: 8080
cors:
  allow-origins: "http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173"

jwt:
  secret: "Rm9yRGV2VGVzdEFWaWVyeUxvbmdBbmRTdHJvbmdTRUNSRVRLZXlTdWl0YWJsZUF0TGVhc3QyNTZCaXRzIQ=="
  issuer: "domaindns"
  expire-minutes: 1440

secrets:
  aes-key: "Dev-Only-Example-AES-Key-Please-Override-In-Prod"

app:
  name: "DomainDNS"
  url: "http://localhost:3000"